apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
  labels:
    app: node-web-app
spec:
  type: NodePort # keep NodePort for minikube / Docker Desktop
  selector:
    app: node-web-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 # fixed port; adjust if taken
